apiVersion: v1
kind: Pod
metadata:
  name: inference
  labels:
    app: inference
spec:
  containers:
    - image: alexeyshevchuk/models:v1
      name: inference
      ports:
        - containerPort: 8000